name: Push to PWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Push to PWS
      env:
        PWS_URL: ${{ secrets.PWS_URL }}
      run: |
        git push --force https://${{ secrets.PWS_USERNAME }}:${{ secrets.PWS_PASSWORD }}@pws.cs.ui.ac.id/${{ secrets.PWS_USERNAME }}/sustainabowl main
